version: 0.2
phases:
  install:
    commands:
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
  pre_build:
      commands:
        - TAG="$REPOSITORY_NAME.$REPOSITORY_BRANCH.$ENVIRONMENT_NAME.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - echo $TAG
        - echo $REPOSITORY_URI_USERS:$TAG
        - echo $REPOSITORY_URI_TASKS:$TAG
        - echo $REPOSITORY_URI_AUTH:$TAG
        - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build -t $REPOSITORY_URI_USERS:latest ./users-api
      - docker build -t $REPOSITORY_URI_TASKS:latest ./tasks-api
      - docker build -t $REPOSITORY_URI_AUTH:latest ./auth-api

  post_build:
    commands:
      - aws s3 cp ./CFT/amazon-eks-vpc.yaml s3://cloudformation-templates-prateek/
      - aws s3 cp ./CFT/eks-cluster.yaml s3://cloudformation-templates-prateek/
      - aws s3 cp ./CFT/eks-ec2.yaml s3://cloudformation-templates-prateek/
      - docker push $REPOSITORY_URI_USERS:latest
      - docker push $REPOSITORY_URI_TASKS:latest
      - docker push $REPOSITORY_URI_AUTH:latest

artifacts:
  files: 
    - CFT/eks-ec2.yaml
    - buildspec-deploy.yml
  discard-paths: yes
